version: '3.6'
services:
  mysql:
    build:
      context: mysql
      dockerfile: Dockerfile
    image: mysql
    container_name: mysql
    ports:
      - 3306:3306
    env_file: mysql/.env
    restart: always
    volumes:
      - DB:/var/lib/mysql
  wordpress:
    build:
      context: wordpress
      dockerfile: Dockerfile
    image: wordpress
    container_name: wordpress
    ports:
      - 9000:9000
    env_file: wordpress/.env
    volumes:
      - Cloud:/var/www/wordpress
    depends_on:
      - mysql
  phpmyadmin:
    build:
      context: phpmyadmin
      dockerfile: Dockerfile
    image: phpmyadmin
    restart: always
    container_name: phpmyadmin
    env_file: phpmyadmin/.env
    ports:
      - 5000:5000
    volumes:
      - Cloud1:/var/www/phpmyadmin
    depends_on:
      - mysql
  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    image: nginx
    container_name: nginx
    volumes:
      - Cloud:/var/www/wordpress
      - Cloud1:/var/www/phpmyadmin
    ports:
      - 80:80
      - 8080:8080
      - 443:443
    restart: on-failure
    depends_on:
      - wordpress
volumes:
  Cloud:
  Cloud1:
  DB: