- name: Add dependency
  apt:
    name: 
      - apt-transport-https 
      - ca-certificates 
      - curl 
      - software-properties-common
    state: present
    update_cache: yes
- name: Add an apt key by id from a docker
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
- name: Add specified repository into sources list
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present
- name: Install python3
  apt:
    name:
      - python3
      - python3-pip
    state: present
    update_cache: yes
- name: Install docker-ce
  apt:
    name:
      - docker-ce
      - docker-compose
    state: present
    update_cache: yes
- name: Install docker using Python3
  pip:
    name: 
      - docker
- name: Copy Dockerfiles to server
  ansible.builtin.copy:
    src: Dockerfiles
    dest: /root
    owner: root
    group: root
    mode: '0644'